version: '3'

services:
  cryptogrambot:
    image: jakkie/cryptogrambot-docker
    build: .
    container_name: cryptogrambot
    restart: always
    volumes:
      - ./appsettings.json:/cryptogrambot/appsettings.json
    ports:
      - 5002:5002
